name: Build the game
run-name: ${{ github.actor }} has triggered a new build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Kitchen Chaos
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Chache the libraries
        uses: actions/cache@v3
        with:
          path: KitchenChaos/Library
          key: Library-${{ matrix.targetPlatform }}
          keys: Library-
      - name: Build the game for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: KitchenChaos
          projectPath: KitchenChaos
      - run: ls -R build
      - name: Upload ${{ matrix.targetPlatform }} build artifact
        uses: actions/upload-artifact@v2
        with:
          name: KitchenChaos-${{ matrix.targetPlatform }}
          path: ./build/${{ matrix.targetPlatform }}

  release:
    name: Release the game
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download StandaloneWindows64 build artifact
        uses: actions/download-artifact@v3
        with:
          name: KitchenChaos-StandaloneWindows64
          path: KitchenChaos-StandaloneWindows64
      - name: Download StandaloneLinux64 build artifact
        uses: actions/download-artifact@v3
        with:
          name: KitchenChaos-StandaloneLinux64
          path: KitchenChaos-StandaloneLinux64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Alpha-Build-${{ github.run_number }}
          release_name: Alpha Build ${{ github.run_number }}
          draft: false
          prerelease: false
      - run: ls -R
      - name: Archive StandaloneWindows64 Release
        uses: thedoctor0/zip-release@main
        with:
          directory: KitchenChaos-StandaloneWindows64
          type: zip
          filename: KitchenChaos-Windows64.zip
      - name: Archive StandaloneLinux64 Release
        uses: thedoctor0/zip-release@main
        with:
          directory: KitchenChaos-StandaloneLinux64
          type: zip
          filename: KitchenChaos-Linux64.zip
      - run: ls -R
      - name: Upload StandaloneWindows64 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KitchenChaos-StandaloneWindows64/KitchenChaos-Windows64.zip
          asset_name: KitchenChaos-Windows64.zip
          asset_content_type: application/zip
      - name: Upload StandaloneLinux64 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KitchenChaos-StandaloneLinux64/KitchenChaos-Linux64.zip
          asset_name: KitchenChaos-Linux64.zip
          asset_content_type: application/zip